import type { DateTime } from 'luxon';

type Day = '0' | '1' | '2' | '3' | '4' | '5' | '6';

export interface Meeting {
  address?: string;
  approximate?: boolean;
  conference_phone?: string;
  conference_phone_notes?: string;
  conference_provider?: string;
  conference_url?: string;
  conference_url_notes?: string;
  contact_1_name?: string;
  contact_1_email?: string;
  contact_1_phone?: string;
  contact_2_name?: string;
  contact_2_email?: string;
  contact_2_phone?: string;
  contact_3_name?: string;
  contact_3_email?: string;
  contact_3_phone?: string;
  day?: Day | Day[];
  distance?: number;
  edit_url?: string | null;
  email?: string;
  end?: DateTime;
  end_time?: `${number}:${number}`;
  feedback_url?: string;
  formatted_address?: string;
  group?: string;
  isActive?: boolean;
  isInPerson?: boolean;
  isOnline?: boolean;
  isTempClosed?: boolean;
  latitude?: number;
  location?: string;
  location_notes?: string;
  longitude?: number;
  minutes_week?: number;
  name?: string;
  notes?: string;
  region?: string;
  regions?: string[];
  search?: string;
  slug: string;
  start?: DateTime;
  time?: `${number}:${number}`;
  timezone?: string;
  types?: MeetingType[];
  updated?: string;
  venmo?: string;
  website?: string;
}
