export const json = [
  {
    slug: 'in-person',
    name: 'In-Person Meeting',
    time: '08:00',
    day: 0,
    types: ['O', 'M', 'X'],
    formatted_address: '123 Test St, Test City, TX 12345, USA',
    timezone: 'America/Chicago',
    regions: ['Texas'],
  },
  {
    slug: 'online',
    name: 'Online Meeting',
    time: '09:00',
    formatted_address: 'New York, NY, USA',
    conference_url: 'https://zoom.us/j/123456789',
    conference_url_notes: 'Meeting ID: 123456789',
    day: 1,
    types: ['O', 'M'],
    timezone: 'America/New_York',
    regions: ['New York'],
  },
  {
    slug: 'inactive',
    name: 'Inactive Meeting',
    time: '10:00',
    formatted_address: 'New York, NY, USA',
    day: 2,
    types: [],
    timezone: 'America/New_York',
    regions: ['New York'],
  },
];
